name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: "1.24"
          check-latest: true
          cache-dependency-path: go.sum
      - name: Download go modules
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: go mod download
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Lint
        run: make vet
      - name: Vuln
        run: make vuln
